name: Deploy Prod Apps

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy apps to prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
